export const GET_COURSES = 'GET_COURSES';
export const GET_COURSES_SUCCESS = 'GET_COURSES_SUCCESS';
export const SAVE_COURSE = 'SAVE_COURSE';
export const SAVE_COURSE_SUCCESS = 'SAVE_COURSE_SUCCESS';
export const VIEW_MODULE = 'VIEW_MODULE';
export const VIEW_MODULE_SUCCESS = 'VIEW_MODULE_SUCCESS';